// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	sqlc "TSVProcessingService/db/sqlc"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// BulkInsertDeviceData mocks base method.
func (m *MockQuerier) BulkInsertDeviceData(ctx context.Context, arg sqlc.BulkInsertDeviceDataParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertDeviceData", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertDeviceData indicates an expected call of BulkInsertDeviceData.
func (mr *MockQuerierMockRecorder) BulkInsertDeviceData(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertDeviceData", reflect.TypeOf((*MockQuerier)(nil).BulkInsertDeviceData), ctx, arg)
}

// CleanupOldApiLogs mocks base method.
func (m *MockQuerier) CleanupOldApiLogs(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldApiLogs", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupOldApiLogs indicates an expected call of CleanupOldApiLogs.
func (mr *MockQuerierMockRecorder) CleanupOldApiLogs(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldApiLogs", reflect.TypeOf((*MockQuerier)(nil).CleanupOldApiLogs), ctx)
}

// CreateApiLog mocks base method.
func (m *MockQuerier) CreateApiLog(ctx context.Context, arg sqlc.CreateApiLogParams) (sqlc.ApiLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApiLog", ctx, arg)
	ret0, _ := ret[0].(sqlc.ApiLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiLog indicates an expected call of CreateApiLog.
func (mr *MockQuerierMockRecorder) CreateApiLog(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiLog", reflect.TypeOf((*MockQuerier)(nil).CreateApiLog), ctx, arg)
}

// CreateDeviceData mocks base method.
func (m *MockQuerier) CreateDeviceData(ctx context.Context, arg sqlc.CreateDeviceDataParams) (sqlc.DeviceDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeviceData", ctx, arg)
	ret0, _ := ret[0].(sqlc.DeviceDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeviceData indicates an expected call of CreateDeviceData.
func (mr *MockQuerierMockRecorder) CreateDeviceData(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeviceData", reflect.TypeOf((*MockQuerier)(nil).CreateDeviceData), ctx, arg)
}

// CreateFile mocks base method.
func (m *MockQuerier) CreateFile(ctx context.Context, arg sqlc.CreateFileParams) (sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFile", ctx, arg)
	ret0, _ := ret[0].(sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFile indicates an expected call of CreateFile.
func (mr *MockQuerierMockRecorder) CreateFile(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*MockQuerier)(nil).CreateFile), ctx, arg)
}

// CreateProcessingError mocks base method.
func (m *MockQuerier) CreateProcessingError(ctx context.Context, arg sqlc.CreateProcessingErrorParams) (sqlc.ProcessingError, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProcessingError", ctx, arg)
	ret0, _ := ret[0].(sqlc.ProcessingError)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProcessingError indicates an expected call of CreateProcessingError.
func (mr *MockQuerierMockRecorder) CreateProcessingError(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProcessingError", reflect.TypeOf((*MockQuerier)(nil).CreateProcessingError), ctx, arg)
}

// CreateReport mocks base method.
func (m *MockQuerier) CreateReport(ctx context.Context, arg sqlc.CreateReportParams) (sqlc.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReport", ctx, arg)
	ret0, _ := ret[0].(sqlc.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReport indicates an expected call of CreateReport.
func (mr *MockQuerierMockRecorder) CreateReport(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReport", reflect.TypeOf((*MockQuerier)(nil).CreateReport), ctx, arg)
}

// DeleteApiLog mocks base method.
func (m *MockQuerier) DeleteApiLog(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApiLog", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApiLog indicates an expected call of DeleteApiLog.
func (mr *MockQuerierMockRecorder) DeleteApiLog(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiLog", reflect.TypeOf((*MockQuerier)(nil).DeleteApiLog), ctx, id)
}

// DeleteDeviceData mocks base method.
func (m *MockQuerier) DeleteDeviceData(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeviceData", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeviceData indicates an expected call of DeleteDeviceData.
func (mr *MockQuerierMockRecorder) DeleteDeviceData(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeviceData", reflect.TypeOf((*MockQuerier)(nil).DeleteDeviceData), ctx, id)
}

// DeleteDeviceDataByFileID mocks base method.
func (m *MockQuerier) DeleteDeviceDataByFileID(ctx context.Context, fileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeviceDataByFileID", ctx, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeviceDataByFileID indicates an expected call of DeleteDeviceDataByFileID.
func (mr *MockQuerierMockRecorder) DeleteDeviceDataByFileID(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeviceDataByFileID", reflect.TypeOf((*MockQuerier)(nil).DeleteDeviceDataByFileID), ctx, fileID)
}

// DeleteFile mocks base method.
func (m *MockQuerier) DeleteFile(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockQuerierMockRecorder) DeleteFile(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockQuerier)(nil).DeleteFile), ctx, id)
}

// DeleteOldFiles mocks base method.
func (m *MockQuerier) DeleteOldFiles(ctx context.Context, status sql.NullString) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldFiles", ctx, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldFiles indicates an expected call of DeleteOldFiles.
func (mr *MockQuerierMockRecorder) DeleteOldFiles(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldFiles", reflect.TypeOf((*MockQuerier)(nil).DeleteOldFiles), ctx, status)
}

// DeleteOldReports mocks base method.
func (m *MockQuerier) DeleteOldReports(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldReports", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldReports indicates an expected call of DeleteOldReports.
func (mr *MockQuerierMockRecorder) DeleteOldReports(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldReports", reflect.TypeOf((*MockQuerier)(nil).DeleteOldReports), ctx)
}

// DeleteProcessingError mocks base method.
func (m *MockQuerier) DeleteProcessingError(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProcessingError", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProcessingError indicates an expected call of DeleteProcessingError.
func (mr *MockQuerierMockRecorder) DeleteProcessingError(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProcessingError", reflect.TypeOf((*MockQuerier)(nil).DeleteProcessingError), ctx, id)
}

// DeleteProcessingErrorsByFile mocks base method.
func (m *MockQuerier) DeleteProcessingErrorsByFile(ctx context.Context, fileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProcessingErrorsByFile", ctx, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProcessingErrorsByFile indicates an expected call of DeleteProcessingErrorsByFile.
func (mr *MockQuerierMockRecorder) DeleteProcessingErrorsByFile(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProcessingErrorsByFile", reflect.TypeOf((*MockQuerier)(nil).DeleteProcessingErrorsByFile), ctx, fileID)
}

// DeleteReport mocks base method.
func (m *MockQuerier) DeleteReport(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReport", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReport indicates an expected call of DeleteReport.
func (mr *MockQuerierMockRecorder) DeleteReport(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReport", reflect.TypeOf((*MockQuerier)(nil).DeleteReport), ctx, id)
}

// GetApiLogByID mocks base method.
func (m *MockQuerier) GetApiLogByID(ctx context.Context, id int64) (sqlc.ApiLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiLogByID", ctx, id)
	ret0, _ := ret[0].(sqlc.ApiLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiLogByID indicates an expected call of GetApiLogByID.
func (mr *MockQuerierMockRecorder) GetApiLogByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiLogByID", reflect.TypeOf((*MockQuerier)(nil).GetApiLogByID), ctx, id)
}

// GetApiStatistics mocks base method.
func (m *MockQuerier) GetApiStatistics(ctx context.Context) ([]sqlc.GetApiStatisticsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiStatistics", ctx)
	ret0, _ := ret[0].([]sqlc.GetApiStatisticsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiStatistics indicates an expected call of GetApiStatistics.
func (mr *MockQuerierMockRecorder) GetApiStatistics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiStatistics", reflect.TypeOf((*MockQuerier)(nil).GetApiStatistics), ctx)
}

// GetDeviceDataByFileID mocks base method.
func (m *MockQuerier) GetDeviceDataByFileID(ctx context.Context, fileID int64) ([]sqlc.DeviceDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceDataByFileID", ctx, fileID)
	ret0, _ := ret[0].([]sqlc.DeviceDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceDataByFileID indicates an expected call of GetDeviceDataByFileID.
func (mr *MockQuerierMockRecorder) GetDeviceDataByFileID(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceDataByFileID", reflect.TypeOf((*MockQuerier)(nil).GetDeviceDataByFileID), ctx, fileID)
}

// GetDeviceDataByID mocks base method.
func (m *MockQuerier) GetDeviceDataByID(ctx context.Context, id int64) (sqlc.DeviceDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceDataByID", ctx, id)
	ret0, _ := ret[0].(sqlc.DeviceDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceDataByID indicates an expected call of GetDeviceDataByID.
func (mr *MockQuerierMockRecorder) GetDeviceDataByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceDataByID", reflect.TypeOf((*MockQuerier)(nil).GetDeviceDataByID), ctx, id)
}

// GetDeviceStatistics mocks base method.
func (m *MockQuerier) GetDeviceStatistics(ctx context.Context, fileID int64) (sqlc.GetDeviceStatisticsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceStatistics", ctx, fileID)
	ret0, _ := ret[0].(sqlc.GetDeviceStatisticsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceStatistics indicates an expected call of GetDeviceStatistics.
func (mr *MockQuerierMockRecorder) GetDeviceStatistics(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceStatistics", reflect.TypeOf((*MockQuerier)(nil).GetDeviceStatistics), ctx, fileID)
}

// GetFileByFilename mocks base method.
func (m *MockQuerier) GetFileByFilename(ctx context.Context, filename string) (sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByFilename", ctx, filename)
	ret0, _ := ret[0].(sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByFilename indicates an expected call of GetFileByFilename.
func (mr *MockQuerierMockRecorder) GetFileByFilename(ctx, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByFilename", reflect.TypeOf((*MockQuerier)(nil).GetFileByFilename), ctx, filename)
}

// GetFileByID mocks base method.
func (m *MockQuerier) GetFileByID(ctx context.Context, id int64) (sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByID", ctx, id)
	ret0, _ := ret[0].(sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByID indicates an expected call of GetFileByID.
func (mr *MockQuerierMockRecorder) GetFileByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByID", reflect.TypeOf((*MockQuerier)(nil).GetFileByID), ctx, id)
}

// GetProcessingErrorByID mocks base method.
func (m *MockQuerier) GetProcessingErrorByID(ctx context.Context, id int64) (sqlc.ProcessingError, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessingErrorByID", ctx, id)
	ret0, _ := ret[0].(sqlc.ProcessingError)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessingErrorByID indicates an expected call of GetProcessingErrorByID.
func (mr *MockQuerierMockRecorder) GetProcessingErrorByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessingErrorByID", reflect.TypeOf((*MockQuerier)(nil).GetProcessingErrorByID), ctx, id)
}

// GetReportByID mocks base method.
func (m *MockQuerier) GetReportByID(ctx context.Context, id int64) (sqlc.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportByID indicates an expected call of GetReportByID.
func (mr *MockQuerierMockRecorder) GetReportByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportByID", reflect.TypeOf((*MockQuerier)(nil).GetReportByID), ctx, id)
}

// GetReportsByDateRange mocks base method.
func (m *MockQuerier) GetReportsByDateRange(ctx context.Context, arg sqlc.GetReportsByDateRangeParams) ([]sqlc.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportsByDateRange", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportsByDateRange indicates an expected call of GetReportsByDateRange.
func (mr *MockQuerierMockRecorder) GetReportsByDateRange(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportsByDateRange", reflect.TypeOf((*MockQuerier)(nil).GetReportsByDateRange), ctx, arg)
}

// GetReportsByUnit mocks base method.
func (m *MockQuerier) GetReportsByUnit(ctx context.Context, unitGuid uuid.UUID) ([]sqlc.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportsByUnit", ctx, unitGuid)
	ret0, _ := ret[0].([]sqlc.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportsByUnit indicates an expected call of GetReportsByUnit.
func (mr *MockQuerierMockRecorder) GetReportsByUnit(ctx, unitGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportsByUnit", reflect.TypeOf((*MockQuerier)(nil).GetReportsByUnit), ctx, unitGuid)
}

// ListApiErrors mocks base method.
func (m *MockQuerier) ListApiErrors(ctx context.Context, statusCode sql.NullInt32) ([]sqlc.ApiLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApiErrors", ctx, statusCode)
	ret0, _ := ret[0].([]sqlc.ApiLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApiErrors indicates an expected call of ListApiErrors.
func (mr *MockQuerierMockRecorder) ListApiErrors(ctx, statusCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApiErrors", reflect.TypeOf((*MockQuerier)(nil).ListApiErrors), ctx, statusCode)
}

// ListApiLogs mocks base method.
func (m *MockQuerier) ListApiLogs(ctx context.Context, arg sqlc.ListApiLogsParams) ([]sqlc.ApiLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApiLogs", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ApiLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApiLogs indicates an expected call of ListApiLogs.
func (mr *MockQuerierMockRecorder) ListApiLogs(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApiLogs", reflect.TypeOf((*MockQuerier)(nil).ListApiLogs), ctx, arg)
}

// ListApiLogsByEndpoint mocks base method.
func (m *MockQuerier) ListApiLogsByEndpoint(ctx context.Context, endpoint string) ([]sqlc.ApiLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApiLogsByEndpoint", ctx, endpoint)
	ret0, _ := ret[0].([]sqlc.ApiLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApiLogsByEndpoint indicates an expected call of ListApiLogsByEndpoint.
func (mr *MockQuerierMockRecorder) ListApiLogsByEndpoint(ctx, endpoint interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApiLogsByEndpoint", reflect.TypeOf((*MockQuerier)(nil).ListApiLogsByEndpoint), ctx, endpoint)
}

// ListApiLogsByUnit mocks base method.
func (m *MockQuerier) ListApiLogsByUnit(ctx context.Context, unitGuid uuid.NullUUID) ([]sqlc.ApiLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApiLogsByUnit", ctx, unitGuid)
	ret0, _ := ret[0].([]sqlc.ApiLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApiLogsByUnit indicates an expected call of ListApiLogsByUnit.
func (mr *MockQuerierMockRecorder) ListApiLogsByUnit(ctx, unitGuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApiLogsByUnit", reflect.TypeOf((*MockQuerier)(nil).ListApiLogsByUnit), ctx, unitGuid)
}

// ListDeviceDataByClass mocks base method.
func (m *MockQuerier) ListDeviceDataByClass(ctx context.Context, arg sqlc.ListDeviceDataByClassParams) ([]sqlc.DeviceDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeviceDataByClass", ctx, arg)
	ret0, _ := ret[0].([]sqlc.DeviceDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeviceDataByClass indicates an expected call of ListDeviceDataByClass.
func (mr *MockQuerierMockRecorder) ListDeviceDataByClass(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeviceDataByClass", reflect.TypeOf((*MockQuerier)(nil).ListDeviceDataByClass), ctx, arg)
}

// ListDeviceDataByUnit mocks base method.
func (m *MockQuerier) ListDeviceDataByUnit(ctx context.Context, arg sqlc.ListDeviceDataByUnitParams) ([]sqlc.DeviceDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeviceDataByUnit", ctx, arg)
	ret0, _ := ret[0].([]sqlc.DeviceDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeviceDataByUnit indicates an expected call of ListDeviceDataByUnit.
func (mr *MockQuerierMockRecorder) ListDeviceDataByUnit(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeviceDataByUnit", reflect.TypeOf((*MockQuerier)(nil).ListDeviceDataByUnit), ctx, arg)
}

// ListFiles mocks base method.
func (m *MockQuerier) ListFiles(ctx context.Context, arg sqlc.ListFilesParams) ([]sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", ctx, arg)
	ret0, _ := ret[0].([]sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockQuerierMockRecorder) ListFiles(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockQuerier)(nil).ListFiles), ctx, arg)
}

// ListFilesByDateRange mocks base method.
func (m *MockQuerier) ListFilesByDateRange(ctx context.Context, arg sqlc.ListFilesByDateRangeParams) ([]sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilesByDateRange", ctx, arg)
	ret0, _ := ret[0].([]sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilesByDateRange indicates an expected call of ListFilesByDateRange.
func (mr *MockQuerierMockRecorder) ListFilesByDateRange(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesByDateRange", reflect.TypeOf((*MockQuerier)(nil).ListFilesByDateRange), ctx, arg)
}

// ListFilesByStatus mocks base method.
func (m *MockQuerier) ListFilesByStatus(ctx context.Context, status sql.NullString) ([]sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilesByStatus", ctx, status)
	ret0, _ := ret[0].([]sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilesByStatus indicates an expected call of ListFilesByStatus.
func (mr *MockQuerierMockRecorder) ListFilesByStatus(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesByStatus", reflect.TypeOf((*MockQuerier)(nil).ListFilesByStatus), ctx, status)
}

// ListProcessingErrorsByFile mocks base method.
func (m *MockQuerier) ListProcessingErrorsByFile(ctx context.Context, fileID int64) ([]sqlc.ProcessingError, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProcessingErrorsByFile", ctx, fileID)
	ret0, _ := ret[0].([]sqlc.ProcessingError)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProcessingErrorsByFile indicates an expected call of ListProcessingErrorsByFile.
func (mr *MockQuerierMockRecorder) ListProcessingErrorsByFile(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProcessingErrorsByFile", reflect.TypeOf((*MockQuerier)(nil).ListProcessingErrorsByFile), ctx, fileID)
}

// ListProcessingErrorsSummary mocks base method.
func (m *MockQuerier) ListProcessingErrorsSummary(ctx context.Context, fileID int64) ([]sqlc.ListProcessingErrorsSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProcessingErrorsSummary", ctx, fileID)
	ret0, _ := ret[0].([]sqlc.ListProcessingErrorsSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProcessingErrorsSummary indicates an expected call of ListProcessingErrorsSummary.
func (mr *MockQuerierMockRecorder) ListProcessingErrorsSummary(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProcessingErrorsSummary", reflect.TypeOf((*MockQuerier)(nil).ListProcessingErrorsSummary), ctx, fileID)
}

// ListRecentReports mocks base method.
func (m *MockQuerier) ListRecentReports(ctx context.Context, arg sqlc.ListRecentReportsParams) ([]sqlc.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentReports", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentReports indicates an expected call of ListRecentReports.
func (mr *MockQuerierMockRecorder) ListRecentReports(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentReports", reflect.TypeOf((*MockQuerier)(nil).ListRecentReports), ctx, arg)
}

// ListSlowRequests mocks base method.
func (m *MockQuerier) ListSlowRequests(ctx context.Context, responseTimeMs sql.NullInt32) ([]sqlc.ApiLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSlowRequests", ctx, responseTimeMs)
	ret0, _ := ret[0].([]sqlc.ApiLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSlowRequests indicates an expected call of ListSlowRequests.
func (mr *MockQuerierMockRecorder) ListSlowRequests(ctx, responseTimeMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSlowRequests", reflect.TypeOf((*MockQuerier)(nil).ListSlowRequests), ctx, responseTimeMs)
}

// SearchDeviceDataText mocks base method.
func (m *MockQuerier) SearchDeviceDataText(ctx context.Context, arg sqlc.SearchDeviceDataTextParams) ([]sqlc.DeviceDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDeviceDataText", ctx, arg)
	ret0, _ := ret[0].([]sqlc.DeviceDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDeviceDataText indicates an expected call of SearchDeviceDataText.
func (mr *MockQuerierMockRecorder) SearchDeviceDataText(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDeviceDataText", reflect.TypeOf((*MockQuerier)(nil).SearchDeviceDataText), ctx, arg)
}

// UpdateApiLog mocks base method.
func (m *MockQuerier) UpdateApiLog(ctx context.Context, arg sqlc.UpdateApiLogParams) (sqlc.ApiLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateApiLog", ctx, arg)
	ret0, _ := ret[0].(sqlc.ApiLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateApiLog indicates an expected call of UpdateApiLog.
func (mr *MockQuerierMockRecorder) UpdateApiLog(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApiLog", reflect.TypeOf((*MockQuerier)(nil).UpdateApiLog), ctx, arg)
}

// UpdateDeviceData mocks base method.
func (m *MockQuerier) UpdateDeviceData(ctx context.Context, arg sqlc.UpdateDeviceDataParams) (sqlc.DeviceDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceData", ctx, arg)
	ret0, _ := ret[0].(sqlc.DeviceDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeviceData indicates an expected call of UpdateDeviceData.
func (mr *MockQuerierMockRecorder) UpdateDeviceData(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceData", reflect.TypeOf((*MockQuerier)(nil).UpdateDeviceData), ctx, arg)
}

// UpdateFileProgress mocks base method.
func (m *MockQuerier) UpdateFileProgress(ctx context.Context, arg sqlc.UpdateFileProgressParams) (sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileProgress", ctx, arg)
	ret0, _ := ret[0].(sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFileProgress indicates an expected call of UpdateFileProgress.
func (mr *MockQuerierMockRecorder) UpdateFileProgress(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileProgress", reflect.TypeOf((*MockQuerier)(nil).UpdateFileProgress), ctx, arg)
}

// UpdateFileStatus mocks base method.
func (m *MockQuerier) UpdateFileStatus(ctx context.Context, arg sqlc.UpdateFileStatusParams) (sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFileStatus indicates an expected call of UpdateFileStatus.
func (mr *MockQuerierMockRecorder) UpdateFileStatus(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateFileStatus), ctx, arg)
}

// UpdateFileWithError mocks base method.
func (m *MockQuerier) UpdateFileWithError(ctx context.Context, arg sqlc.UpdateFileWithErrorParams) (sqlc.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileWithError", ctx, arg)
	ret0, _ := ret[0].(sqlc.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFileWithError indicates an expected call of UpdateFileWithError.
func (mr *MockQuerierMockRecorder) UpdateFileWithError(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileWithError", reflect.TypeOf((*MockQuerier)(nil).UpdateFileWithError), ctx, arg)
}

// UpdateProcessingError mocks base method.
func (m *MockQuerier) UpdateProcessingError(ctx context.Context, arg sqlc.UpdateProcessingErrorParams) (sqlc.ProcessingError, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingError", ctx, arg)
	ret0, _ := ret[0].(sqlc.ProcessingError)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProcessingError indicates an expected call of UpdateProcessingError.
func (mr *MockQuerierMockRecorder) UpdateProcessingError(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingError", reflect.TypeOf((*MockQuerier)(nil).UpdateProcessingError), ctx, arg)
}

// UpdateReportPath mocks base method.
func (m *MockQuerier) UpdateReportPath(ctx context.Context, arg sqlc.UpdateReportPathParams) (sqlc.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReportPath", ctx, arg)
	ret0, _ := ret[0].(sqlc.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReportPath indicates an expected call of UpdateReportPath.
func (mr *MockQuerierMockRecorder) UpdateReportPath(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReportPath", reflect.TypeOf((*MockQuerier)(nil).UpdateReportPath), ctx, arg)
}
