// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_log.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cleanupOldApiLogs = `-- name: CleanupOldApiLogs :exec
DELETE FROM api_logs
WHERE created_at < now() - interval '30 days'
`

func (q *Queries) CleanupOldApiLogs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupOldApiLogs)
	return err
}

const createApiLog = `-- name: CreateApiLog :one
INSERT INTO api_logs (
    endpoint,
    unit_guid,
    response_time_ms,
    status_code
) VALUES (
    $1, $2, $3, $4
) RETURNING id, endpoint, unit_guid, response_time_ms, status_code, created_at
`

type CreateApiLogParams struct {
	Endpoint       string        `json:"endpoint"`
	UnitGuid       uuid.NullUUID `json:"unit_guid"`
	ResponseTimeMs sql.NullInt32 `json:"response_time_ms"`
	StatusCode     sql.NullInt32 `json:"status_code"`
}

func (q *Queries) CreateApiLog(ctx context.Context, arg CreateApiLogParams) (ApiLog, error) {
	row := q.db.QueryRowContext(ctx, createApiLog,
		arg.Endpoint,
		arg.UnitGuid,
		arg.ResponseTimeMs,
		arg.StatusCode,
	)
	var i ApiLog
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.UnitGuid,
		&i.ResponseTimeMs,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApiLog = `-- name: DeleteApiLog :exec
DELETE FROM api_logs
WHERE id = $1
`

func (q *Queries) DeleteApiLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteApiLog, id)
	return err
}

const getApiLogByID = `-- name: GetApiLogByID :one
SELECT id, endpoint, unit_guid, response_time_ms, status_code, created_at FROM api_logs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApiLogByID(ctx context.Context, id int64) (ApiLog, error) {
	row := q.db.QueryRowContext(ctx, getApiLogByID, id)
	var i ApiLog
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.UnitGuid,
		&i.ResponseTimeMs,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}

const getApiStatistics = `-- name: GetApiStatistics :many
SELECT
    endpoint,
    COUNT(*) as request_count,
    AVG(response_time_ms)::int as avg_response_time,
    COUNT(CASE WHEN status_code >= 400 THEN 1 END) as error_count
FROM api_logs
WHERE created_at >= now() - interval '1 day'
GROUP BY endpoint
ORDER BY request_count DESC
`

type GetApiStatisticsRow struct {
	Endpoint        string `json:"endpoint"`
	RequestCount    int64  `json:"request_count"`
	AvgResponseTime int32  `json:"avg_response_time"`
	ErrorCount      int64  `json:"error_count"`
}

func (q *Queries) GetApiStatistics(ctx context.Context) ([]GetApiStatisticsRow, error) {
	rows, err := q.db.QueryContext(ctx, getApiStatistics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApiStatisticsRow
	for rows.Next() {
		var i GetApiStatisticsRow
		if err := rows.Scan(
			&i.Endpoint,
			&i.RequestCount,
			&i.AvgResponseTime,
			&i.ErrorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiErrors = `-- name: ListApiErrors :many
SELECT id, endpoint, unit_guid, response_time_ms, status_code, created_at FROM api_logs
WHERE status_code >= $1
ORDER BY created_at DESC
`

func (q *Queries) ListApiErrors(ctx context.Context, statusCode sql.NullInt32) ([]ApiLog, error) {
	rows, err := q.db.QueryContext(ctx, listApiErrors, statusCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiLog
	for rows.Next() {
		var i ApiLog
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.UnitGuid,
			&i.ResponseTimeMs,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiLogs = `-- name: ListApiLogs :many
SELECT id, endpoint, unit_guid, response_time_ms, status_code, created_at FROM api_logs
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListApiLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListApiLogs(ctx context.Context, arg ListApiLogsParams) ([]ApiLog, error) {
	rows, err := q.db.QueryContext(ctx, listApiLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiLog
	for rows.Next() {
		var i ApiLog
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.UnitGuid,
			&i.ResponseTimeMs,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiLogsByEndpoint = `-- name: ListApiLogsByEndpoint :many
SELECT id, endpoint, unit_guid, response_time_ms, status_code, created_at FROM api_logs
WHERE endpoint = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApiLogsByEndpoint(ctx context.Context, endpoint string) ([]ApiLog, error) {
	rows, err := q.db.QueryContext(ctx, listApiLogsByEndpoint, endpoint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiLog
	for rows.Next() {
		var i ApiLog
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.UnitGuid,
			&i.ResponseTimeMs,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiLogsByUnit = `-- name: ListApiLogsByUnit :many
SELECT id, endpoint, unit_guid, response_time_ms, status_code, created_at FROM api_logs
WHERE unit_guid = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApiLogsByUnit(ctx context.Context, unitGuid uuid.NullUUID) ([]ApiLog, error) {
	rows, err := q.db.QueryContext(ctx, listApiLogsByUnit, unitGuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiLog
	for rows.Next() {
		var i ApiLog
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.UnitGuid,
			&i.ResponseTimeMs,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlowRequests = `-- name: ListSlowRequests :many
SELECT id, endpoint, unit_guid, response_time_ms, status_code, created_at FROM api_logs
WHERE response_time_ms > $1
ORDER BY response_time_ms DESC
`

func (q *Queries) ListSlowRequests(ctx context.Context, responseTimeMs sql.NullInt32) ([]ApiLog, error) {
	rows, err := q.db.QueryContext(ctx, listSlowRequests, responseTimeMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiLog
	for rows.Next() {
		var i ApiLog
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.UnitGuid,
			&i.ResponseTimeMs,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiLog = `-- name: UpdateApiLog :one
UPDATE api_logs
SET
    response_time_ms = $2
WHERE id = $1
RETURNING id, endpoint, unit_guid, response_time_ms, status_code, created_at
`

type UpdateApiLogParams struct {
	ID             int64         `json:"id"`
	ResponseTimeMs sql.NullInt32 `json:"response_time_ms"`
}

func (q *Queries) UpdateApiLog(ctx context.Context, arg UpdateApiLogParams) (ApiLog, error) {
	row := q.db.QueryRowContext(ctx, updateApiLog, arg.ID, arg.ResponseTimeMs)
	var i ApiLog
	err := row.Scan(
		&i.ID,
		&i.Endpoint,
		&i.UnitGuid,
		&i.ResponseTimeMs,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}
