// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type ApiLog struct {
	ID             int64         `json:"id"`
	Endpoint       string        `json:"endpoint"`
	UnitGuid       uuid.NullUUID `json:"unit_guid"`
	ResponseTimeMs sql.NullInt32 `json:"response_time_ms"`
	StatusCode     sql.NullInt32 `json:"status_code"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}

type DeviceDatum struct {
	ID         int64          `json:"id"`
	FileID     int64          `json:"file_id"`
	UnitGuid   uuid.UUID      `json:"unit_guid"`
	Mqtt       sql.NullString `json:"mqtt"`
	Invid      sql.NullString `json:"invid"`
	MsgID      sql.NullString `json:"msg_id"`
	Text       sql.NullString `json:"text"`
	Context    sql.NullString `json:"context"`
	Class      sql.NullString `json:"class"`
	Level      sql.NullInt32  `json:"level"`
	Area       sql.NullString `json:"area"`
	Addr       sql.NullString `json:"addr"`
	Block      sql.NullString `json:"block"`
	Type       sql.NullString `json:"type"`
	Bit        sql.NullInt32  `json:"bit"`
	InvertBit  sql.NullBool   `json:"invert_bit"`
	LineNumber int32          `json:"line_number"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type File struct {
	ID            int64          `json:"id"`
	Filename      string         `json:"filename"`
	FileHash      string         `json:"file_hash"`
	Status        sql.NullString `json:"status"`
	RowsProcessed sql.NullInt32  `json:"rows_processed"`
	RowsFailed    sql.NullInt32  `json:"rows_failed"`
	ErrorMessage  sql.NullString `json:"error_message"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type ProcessingError struct {
	ID           int64          `json:"id"`
	FileID       int64          `json:"file_id"`
	LineNumber   sql.NullInt32  `json:"line_number"`
	RawLine      sql.NullString `json:"raw_line"`
	ErrorMessage string         `json:"error_message"`
	FieldName    sql.NullString `json:"field_name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Report struct {
	ID          int64          `json:"id"`
	UnitGuid    uuid.UUID      `json:"unit_guid"`
	ReportType  sql.NullString `json:"report_type"`
	FilePath    string         `json:"file_path"`
	GeneratedAt sql.NullTime   `json:"generated_at"`
}
