// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    unit_guid,
    report_type,
    file_path
) VALUES (
    $1, $2, $3
) RETURNING id, unit_guid, report_type, file_path, generated_at
`

type CreateReportParams struct {
	UnitGuid   uuid.UUID      `json:"unit_guid"`
	ReportType sql.NullString `json:"report_type"`
	FilePath   string         `json:"file_path"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport, arg.UnitGuid, arg.ReportType, arg.FilePath)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UnitGuid,
		&i.ReportType,
		&i.FilePath,
		&i.GeneratedAt,
	)
	return i, err
}

const deleteOldReports = `-- name: DeleteOldReports :exec
DELETE FROM reports
WHERE generated_at < now() - interval '365 days'
`

func (q *Queries) DeleteOldReports(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldReports)
	return err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports
WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReport, id)
	return err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, unit_guid, report_type, file_path, generated_at FROM reports
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReportByID(ctx context.Context, id int64) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UnitGuid,
		&i.ReportType,
		&i.FilePath,
		&i.GeneratedAt,
	)
	return i, err
}

const getReportsByDateRange = `-- name: GetReportsByDateRange :many
SELECT id, unit_guid, report_type, file_path, generated_at FROM reports
WHERE generated_at BETWEEN $1 AND $2
ORDER BY generated_at DESC
`

type GetReportsByDateRangeParams struct {
	GeneratedAt   sql.NullTime `json:"generated_at"`
	GeneratedAt_2 sql.NullTime `json:"generated_at_2"`
}

func (q *Queries) GetReportsByDateRange(ctx context.Context, arg GetReportsByDateRangeParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, getReportsByDateRange, arg.GeneratedAt, arg.GeneratedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UnitGuid,
			&i.ReportType,
			&i.FilePath,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByUnit = `-- name: GetReportsByUnit :many
SELECT id, unit_guid, report_type, file_path, generated_at FROM reports
WHERE unit_guid = $1
ORDER BY generated_at DESC
`

func (q *Queries) GetReportsByUnit(ctx context.Context, unitGuid uuid.UUID) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, getReportsByUnit, unitGuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UnitGuid,
			&i.ReportType,
			&i.FilePath,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentReports = `-- name: ListRecentReports :many
SELECT id, unit_guid, report_type, file_path, generated_at FROM reports
ORDER BY generated_at DESC
LIMIT $1
OFFSET $2
`

type ListRecentReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecentReports(ctx context.Context, arg ListRecentReportsParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listRecentReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UnitGuid,
			&i.ReportType,
			&i.FilePath,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportPath = `-- name: UpdateReportPath :one
UPDATE reports
SET
    file_path = $2
WHERE id = $1
RETURNING id, unit_guid, report_type, file_path, generated_at
`

type UpdateReportPathParams struct {
	ID       int64  `json:"id"`
	FilePath string `json:"file_path"`
}

func (q *Queries) UpdateReportPath(ctx context.Context, arg UpdateReportPathParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, updateReportPath, arg.ID, arg.FilePath)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UnitGuid,
		&i.ReportType,
		&i.FilePath,
		&i.GeneratedAt,
	)
	return i, err
}
